CREATE TABLE tab_user (
  id_user BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(50) NOT NULL,
   username VARCHAR(20) NOT NULL,
   password VARCHAR(100) NOT NULL,
   CONSTRAINT pk_tab_user PRIMARY KEY (id_user)
);

CREATE TABLE tab_user_roles (
  user_id BIGINT NOT NULL,
   role_id VARCHAR(255)
);

ALTER TABLE tab_user ADD CONSTRAINT uc_tab_user_username UNIQUE (username);

ALTER TABLE tab_user_roles ADD CONSTRAINT fk_tab_user_roles_on_user FOREIGN KEY (user_id) REFERENCES tab_user (id_user);